name: Build Dylib
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Randomblock1/theos-action@v1
      - name: Build Tweak
        env:
          THEOS_PATH: ${{ github.workspace }}/theos
        run: make package FINALPACKAGE=      
      - uses: actions/upload-artifact@v4
        with:
          name: dylib-output
          path: |
            .theos/obj/*.dylib
            packages/*.deb
